version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: barflow/api:upload
    ports:
    - "3000:3000"
    links:
    - mongo
    environment:
      - DB=$DB
      - JWT_SECRET=$JWT_SECRET
      - NODE_ENV=$NODE_ENV
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  mongo:
    image: mongo:3.2
    ports:
    - "27017:27017"
    volumes:
    - ./data:/data/db
