version: '2'
services:
  lb:
    image: barflow/lb:latest
    links:
      - api_v1
      - api_v2
      - salespage
    ports:
      - "80:80"
  api_v1:
    image: barflow/api:latest
    # ports:
    # - "3000"
    depends_on:
    - mongo
    environment:
      - DB=$DB
      - JWT_SECRET=$JWT_SECRET
      - NODE_ENV=$NODE_ENV
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  api_v2:
    image: barflow/api:v2
    # ports:
    # - "3000"
    depends_on:
    - mongo
    environment:
      - DB=$DB
      - JWT_SECRET=$JWT_SECRET
      - NODE_ENV=$NODE_ENV
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  salespage:
    image: barflow/salespage
    # ports:
    # - "8080"
    # environment:
    #   - VIRTUAL_HOST=barflow.io
  mongo:
    image: mongo:3.2
    # ports:
    # - "27017"
    volumes:
    - ./data:/data/db
